<form id="custom-form" class="form perfect-draft" aria-labelledby="form-heading">

    <fieldset>
        <legend id="form-heading" class="form-heading">Please fill out the form below</legend>

        <div class="field required">
            <label for="name" class="label">
                <span>Name</span>
            </label>
            <div class="control">
                <input type="text" id="name" name="name" class="input-text" aria-required="true" required>
            </div>
        </div>

        <div class="field required">
            <label for="dob" class="label">
                <span>Date of Birth</span>
            </label>
            <div class="control">
                <input type="date" id="dob" name="dob" class="input-text" aria-required="true" required>
            </div>
        </div>

        <div class="field required">
            <label for="email" class="label">
                <span>Email</span>
            </label>
            <div class="control">
                <input type="email" id="email" name="email" class="input-text" aria-required="true" required>
            </div>
        </div>

        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="Submit">
                    <span>Submit</span>
                </button>
            </div>
        </div>
    </fieldset>
</form>

<script type="text/x-magento-init">
{
    "#custom-form": {
        "customFormDialog": {}
    }
}
</script>
